### PR TITLE
Adding E-Mail Text for "Dog or cat Detected"

### PR DESCRIPTION
**Pull request by flosch-dev**

### CODE REVIEW

**Comment by flosch-dev** [comment]
this went to fast ... I still wanted to test it first. I will give an update if it works

**Comment by flosch-dev** [comment]
The change was working fine. Maybe some background... I'm using RLC-810A with latest FW v3.1.0.956_22041503.
In that case, the E-Mail Text for Pet detection seems to be changed from the initial one "Pet Detected" to "Dog or cat Detected".
I just added the Text I was receiving, but left the other still there for compatibility reasons.
Feel free to merge this PR. Anything I need to change in changelog or other?

**Comment by cpainchaud** [comment]
Hi, My main issue is your second commit where you're are editing the projects urls .... I don't get what's doing here :D

**Comment by flosch-dev** [comment]
Sorry, this was not my intention. I was not sure whether I need the other changes for testing the change first from different repo.
The other commit is removed. Hope it is OK now.

**Review by cpainchaud — APPROVED** [review]

**Pull request merged**
