### PR TITLE
Re-Implmented simpler thumbnailing

### PR DESCRIPTION
**Pull request by xannor**
This is a re-do of the thumb nailing code as I was not happy with the outcome of the previous attempt. 

This is currently a draft as I have more work to do but I welcome any feedback or changes that may be needed

~~TODO:~~

- [x] Services needed:
  - [x] ~~Clear existing thumbnails for playbacks~~
  - [ ] ~~Set custom playback thumbnail folder~~Moved to config option
  - [ ] ~~Generate thumbnails for playbacks in a given date range and seconds offset~~
  - [x] Query camera for VoDs
- [ ] ~~Optimizations:~~
  - [x] ~~Service to query camera and commit thumbnails on demand (could be called in an automation daily)~~
  - [x] ~~Services to query camera and purge missing vods (could be called in daily automation)~~
  - [ ] ~~Option to either disable thumbnails or to only hold in memory and limit how much?~~
- [x] Custom parts
  - [x] Script helpers (these use only the device and not an specifict entity)
    - [x] device trigger for new recording
    - [x] device condition for present/missing thumbnail of last/current recording
    - [x] device action for saving a current capture as the last/current recording thumbnail
  - [x] blueprint for basic/simple video capture thumbnails: https://gist.github.com/xannor/31256694f2a2aa332355cba20a9ea823

~~minimized the thumbnail generation to only grabbing a cap during a motion event. This should be fairly lightweight for any environment, however since I do not know the correct "timestamp" for the vod (as the pre-record settings can vary) I hold the cap in memory until the browse media happens, then I pair them up when I query the camera list.~~

~~The media source attempts to save held thumbs on shutdown and will pull them back into memory on startup.~~

~~When a held thumbnail is paired to a vod, it is written to the thumbnail storage folder. This folder is either an internal one under storage, or the last one configured (not implemented yet.)~~

~~I want to shift cleanup and thumbnail generation to services so the user can decided if/when they happen as I could think of no happy medium to do it automatically without having some sort of issue~~

Edit:
I stroked the previous since my outcome has changed since initially submitted, though the concept remains the same.

My end result is the following:
Created a separate sensor to manage/track the current/last recording, this sensor should not be present on cameras that do not support recording, though this will probably need to be fine tuned, also may want to create the sensor as disabled so someone has to "opt-in" to the recording and thumbnail support (could also tie in the media source component to this as well.)
Added additional convenience attributes to both the binary_sensor and camera. These allow for better usage in scripts as the back-end motion event and a url for the last video are provided as attributes. Similar attributes are also provided by the last event sensor.
Added additional convenience components to the integration, device_actions, device_conditions, and device_trigger. These were added to simplify the thumbnail blueprint (so it only needs a device and not each component)

If you don't want the "ugly" commit history, I can cancel this pull and "Roll-up" the changes into one single commit and do a new pull.

### CODE REVIEW

**Comment by xannor** [comment]
Researching:

For the "backlogged" vod thumbnails, I need to see how to create a long running task/process properly in HA. This is because, at least for my PI4, ffmpeg is not optimized and performs poorly. MY idea is to have the service queue up the vods and a task/process process the queue one at a time. I need to find out how to handle notifications and updates for that. This may require another sensor that handles reports, but I wan to see what the "official" approach is first.

**Comment by xannor** [comment]
Revising the "Backlogged" vod issue. Instead of building the generation into the component (and the associated deps) I decided that this is a tas kbesk left to the user, however I plan to build some guidence. 

1) creating a service that will "query" the vods and dump the results to the event bus (1 event per vod) this will allow the user to create an automation that triggers off of the event and processes a file. They would also have control over how many processes and run at a time.
2) create a blueprint for a basic automation that would listen for the event and sequentially pass the vods through ffmpeg to generate the thumbnails. This blueprint should probably be stored in a separate repo so it can be updated independent of the main integration.

**Comment by xannor** [comment]
Dropping the backlogged for now, both my test environment and my actual server (RPI4) are not suitable for using FFMPEG for much of anything. I did implement the snapshotting and storage, and the current commit "first trial build" is one I am running on my live server with three cameras to see hor it performs.

It currently will default to capturing thumbnails holding them in memory, only storing them in the /config/.storage folder in either a media browse or by calling the commit thumbnails service. I have hooks for a config setting to specify a permanent thumbnail folder, per camera, but I have not implemented the config yet.

The query vod server requires an event_id, any string can be used, and it will dump all the VoDs on the camera (limit-able by a start and end date range) to that event. This can be used to pass info to some other process to create thumbnails from the vods. It will supply a url with a long-lived token (until restart), the start/end/filenames, and whether a thumbnail exists and the path is is/should be under. 

I am leaving the moving of the thumbnails and any post thumbnail generation as a user challange. 

The default folder for thumbnails is /config/.storage/reolink_dev/{camera unique id}

On shutdown and restart any in-memory thumbnails are saved to disk and reloaded on start. This is because I cannot always match up the time the motion occurred with the actual start/end dates the camera will store until a search against the camera is performed.

The only major issue with this is that it is date/time sensitive, so if the camera and system clocks are too far out of sync it may not be able to match up thumbnails, the timezone of the camera is currently not taken into account so timezone could also be an issue. I don't know if that information is available via the API.

Once I have a few days of live data without errors I will probably submit this as it.

**Comment by xannor** [comment]
So far so good. I realized I disabled the VoD redirector that the query event needs (this "protects" the url from the auth token, ensuring that when it is requested a current auth token and connection is made) I also removed a small cache and are just passing the filename instead, this will resolve some browser caching issues I would occasionally see. I'm going to let this run on my system overnight and if I get no errors by morning I will probably submit the pull.

**Comment by xannor** [comment]
@fwestenberg  I had a thought overnight and I would like your input. In watching my thumbnail code, I had originally built it on the idea of the VoD would not be available until after motion stops, however at least with one camera, I noticed that the VoD would be available immediately, and would grow until motion stopped. MY thought it to ditch the sync concepts (and related service) and just manually "sync" a few seconds or a minute after motion capture via a delayed task. 
I would also have to make sure the options to enable thumbnails, and where to store them are back in the config so people can set it up how they want. Do you think I should proceeed as the last change before I submit the pull?

**Comment by xannor** [comment]
I added a sensor to get the last activity (VoD) for cameras that support playback, it should not load if they dont (not tested) I am going to use this as a basis for managing the thumbnails (informationally), and for maintaining some infor in base. I also plan to add a video_url for the most recent VoD to the camera attributes (based on the sensor data and function) I think I am going to scrap the auto thumbnail part and instead leave it up to the user with automations. My reasoning is I just started using DOODS and I want to use its processed image as a thumbnail instead of just the cap, so I can identify what caused the motion. Adding the sensor with the last activity, should inside an automation, provide enough info to save the processed thumbnail to the right spot. This would also remove the need for the flag in config for autocrating the thumbnails.

I know this is taking a long time, but I want to do this right, and I have limited time recently.

**Comment by xannor** [comment]
Gave it a good week of testing and it seems to be working good. I am going to put the finishing touches on the now simple blueprint to capture thumbs with and if all goes smoothly I will submit this tomorrow.

recent changes:
changes some of the sensor attributes to flatten them, and added a custom trigger and action to work with the blueprint and make coordinating automations easier. The trigger is one that works off of the sensor updating with a new video that has no thumbnail, and the action will capture a snapshot and save it to the thumbnail location. Both of these steps can be done via the entities and attributes, the custom trigger and action just simplify for novices and the blueprint.

**Comment by xannor** [comment]
Ok looks good now, so for some stable testing.

If you want to play along, you can use this gist for the blueprint: https://gist.github.com/xannor/31256694f2a2aa332355cba20a9ea823

**Comment by fwestenberg** [comment]
Hi @xannor,

Really great all the effort you've put into this. Is it ready to merge? :-)

**Comment by xannor** [comment]
I have been running it for about a week now with no issues, so I think it should run good.

**Comment by fwestenberg** [comment]
Hi @xannor,

Today I released the new thumbnailing code, together with AI functionality. I get the following error when I try to generate thumbnails:

```
Logger: homeassistant.core
Source: components/recorder/__init__.py:366
First occurred: 13:31:44 (528 occurrences)
Last logged: 13:31:44

Error in event filter
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 717, in async_fire
    if not event_filter(event):
  File "/usr/src/homeassistant/homeassistant/components/recorder/__init__.py", line 366, in _async_event_filter
    entity_id = event.data.get(ATTR_ENTITY_ID)
AttributeError: 'VoDEvent' object has no attribute 'get'
```

At first I got an error on line 99 of sensor.py, so I add an initial check at first:
`if not search or len(search) < 1:`

**Comment by xannor** [comment]
I'll check the code when I get home from work in a couple of hours, it could be a change I made to my local that I forgot to check in or possibly some sort of internationalization issue.

**Pull request merged**
