### PR TITLE
Added HA integration support for stream format

### PR DESCRIPTION
**Pull request by LasseSLambertsen**
Expects a new version of reolink api to be released

### CODE REVIEW

**Comment by LasseSLambertsen** [comment]
Hmm, after testing it on my HA installation, I can conclude that it wont work correctly, as HA does not properly support h265 (HEVC).

So this PR only makes it possible for the user to set the correct settings, but not actually useful...

Perhaps you've got an idea @fwestenberg, I'm not really skilled in Python :)

**Comment by fwestenberg** [comment]
After some reading about this, I conclude the same for now. Apparently not all browsers support h.265 and some hardware like the Raspberry PI may not have enough power to support it also. So for now, I say it won't work unfortunately.

**Comment by fwestenberg** [comment]
Can you please add the code line like I suggested and keep the PR open? Perhaps it will be possible later on.

**Comment by LasseSLambertsen** [comment]
Hmm, what code line is that?
I think I've missed a comment? :)

**Comment by AshtonKem** [comment]
Is there a tracking issue for H265 support in HA? Not being able to use my new RLC-820A in the way that I had hoped is a bummer.

**Comment by andriej** [comment]
When is new API expected to be? 
Will it be in firmare upgrades for cameras?

**Comment by AshtonKem** [comment]
FYI, HA seems to support H256 if you have the ffmpeg integration installed, which I currently do. There must be some integration issue between this addon and the ffmpeg integration.

**Comment by fwestenberg** [comment]
@LasseSLambertsen any chance this will work now? [Here](https://www.home-assistant.io/integrations/stream/) it says it's supported (limited).

**Comment by LasseSLambertsen** [comment]
@fwestenberg Maybe, Will try to find time to test it in the near future

**Comment by LasseSLambertsen** [comment]
@fwestenberg Just had a Quick try, but no luck.

You are more than welcome to try my branch.

**Comment by AshtonKem** [comment]
Testing this with my RLC-810A, this actually works on iOS and Safari, just not in Firefox. 

Probably worth adding a note and merging in.

**Pull request merged**
